{% set name = "BicycleParameters" %}
{% set version = "1.1.0" %}
{% set sha256 = "4c73a2ee11d8e104c32ff620628d58ea277c7aad71f768d0cb40c1df484546d2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - bicycleparameters = bicycleparameters.app:app.run_server
requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - dynamicisttoolkit >=0.5.3
    - matplotlib-base >=3.5.1
    - numpy >=1.21.5
    - python >=3.8
    - scipy >=1.8.0
    - uncertainties >=3.1.5
    - yeadon >=1.3.0
  run_constrained:
    - dash >=2
    - pandas >=1.3.5

test:
  imports:
    - bicycleparameters
    - bicycleparameters.bicycle
    - bicycleparameters.com
    - bicycleparameters.geometry
    - bicycleparameters.inertia
    - bicycleparameters.io
    - bicycleparameters.main
    - bicycleparameters.models
    - bicycleparameters.parameter_sets
    - bicycleparameters.period
    - bicycleparameters.plot
    - bicycleparameters.rider
    - bicycleparameters.tables

about:
  home: http://github.com/moorepants/bicycleparameters
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Generates and manipulates the physical parameters of a bicycle.'
  description: |
    A python program designed to produce and manipulate the basic parameters
    needed for the Whipple bicycle model.
  doc_url: http://bicycleparameters.readthedocs.io/
  dev_url: https://github.com/moorepants/bicycleparameters

extra:
  recipe-maintainers:
    - moorepants
