{% set name = "BicycleParameters" %}
{% set version = "1.2.0" %}
{% set sha256 = "41f6d2aed4d35dccacb5adc33c590367dd9ece7a9e52a4ce0bc3b4ac33080461" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - bicycleparameters = bicycleparameters.app:app.run_server
requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - dynamicisttoolkit >=0.5.3
    - matplotlib-base >=3.5.1
    - numpy >=1.21.5
    - python >=3.8
    - scipy >=1.8.0
    - uncertainties >=3.1.5
    - yeadon >=1.3.0
  run_constrained:
    - dash >=2
    - pandas >=1.3.5

test:
  imports:
    - bicycleparameters
    - bicycleparameters.bicycle
    - bicycleparameters.com
    - bicycleparameters.geometry
    - bicycleparameters.inertia
    - bicycleparameters.io
    - bicycleparameters.main
    - bicycleparameters.models
    - bicycleparameters.parameter_sets
    - bicycleparameters.period
    - bicycleparameters.plot
    - bicycleparameters.rider
    - bicycleparameters.tables

about:
  home: http://github.com/moorepants/bicycleparameters
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Generates and manipulates the physical parameters of a bicycle.'
  description: |
    A python program designed to produce and manipulate the basic parameters
    needed for the Carvallo-Whipple bicycle model and other related models.
  doc_url: http://bicycleparameters.readthedocs.io/
  dev_url: https://github.com/moorepants/bicycleparameters

extra:
  recipe-maintainers:
    - moorepants
