travis:
  secure:
    BINSTAR_TOKEN: GG/zyaq+hHA9Tnl9utj4fv0MjkCoyFI+sX/YJij4Mfunv+pPMluSvcvky5locSepXfdgiLPJLE8avPjVNUmVWTjgebBCBhb4w/PgEaL5P/6kE1STyfUa7bABg5FI+YqQ0+W3xKRaqtmD0y4zq7MPtLHPnCRuFP7VfeKDMMxa6P6JoedZxJFFYu7YqkEy9UP/htz1pKh5O4uWu/neNdFWlP0DNWL+FKCtkwuKcON0TMOmgLc3MIdgAsMwHpPaP0GVUtYmKxlLD8tGqU1lem7JV1NCTweJ1A+INDEtCFNXEMoeLvrZn5OCBvEsESzh4DX1aCdtmXd4+0q80SF3C9MiOofm7cU1FsFPWJghswFdC8ybE6qbkPOQlVI7sGsPYxPI+c4R4Ve96IHu8kytwL/I/p6hYpkBcDXxqls5TSeT4I8IsPvDO9TxgSn+qTbVk/L9mmU1n9lW0gGzrzy4FrzrE+EkcHCww9seNJyfDyPkWpPVjZIqXfoMR0ct/S/qXR88/mS23TR9UI/ikeKRkCiamaYSNalTi8mcz39RH1dCExXnQurFJ4i6Lkjh5505vPdfRBb4OMas55cape1020PE7Iv0P9atBW43vMQ6C2rJA25R9oNZBQXylq3QTcm3yLzgZuTxF1oQbd1HlnWNOpc0e/PZg3HRfL1+YdurxlF+iGg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
