travis:
  secure:
    BINSTAR_TOKEN: G3GtTrHi+Kl4cN7zkC4dwijMtAdeSVXuPE2Autohct95wSCNLTx3hm6x5cfpDMSwkRBb6kSBPSG3zlIL50LB5Jb3tZTJN8ZEpRSEkOMZMzsFybdpQnmOEbHi7DxayfmNnibnCgoE0b+sZuEyH7Fq1/nZX/XhkNhfSudwZ0RnUqN5mYhL0DMJJ6Xn1J4XbcG+tDn6KQqJRYAhss6MZL7rbwRB3WG3kOpJw1GOosCRuZaTlpP539hu73x+TY7tQqKRC79bERe8kYY330ISjNbekAc1Wm1qp8pt1cIpLVw9Od9FC2rlVJ2wrSzazBvz877FaBLoVQmn7PQF7p38x6EKAknoWneALjT9OXX9pCxf8MiW7KHtGkaaeBnNdY8MHRTjnWm1ec172DVRXGlFBMf2kSdBI58Svxqr6SKSzjz+vdVyoLfow3ll/uNl2XpHwf788hYF5DPg9SWfiFvFDCWgH7RexdTOoEPoO4W/M6qbg9zf0TWnOr4uyq53562skEU66xYdNEzEJEKR4UxRG6wTWvB12mVAwZ9W45Z+qu/mksefMiv9eohSUtwjgRaNFxjbGP+jRe8M2rB1OZiRis92wnMP6xj1OpRcBGhgvTRhZCF/1MA5yD5BrY3e5Bn4qY2KRxklTQlU71uZZwRqhB12gdg63FY6xxCfNHTS+cFfDr4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
